const styles = {
  wrapper: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    width: "100%",
    fontFamily: "Arial, sans-serif",
    backgroundColor: "#f0f2f5",
  },
  container: {
    flex: 1,
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 24,
  },
  logoText: {
    margin: 0,
    fontSize: "2rem",
    fontWeight: 700,
    color: "#000",
  },
  subtitulo: {
    fontSize: 14,
    color: "#777",
    marginBottom: 16,
    textAlign: "center",
  },
  searchBox: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 25,
    padding: "10px 16px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
    width: "90%",
    maxWidth: 600,
    margin: "0 auto 32px auto",
    border: "1px solid #ddd",
  },
  searchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    backgroundColor: "transparent",
    fontSize: 16,
    color: "#333",
  },
  listaFavoritos: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 16,
    width: "100%",
    maxWidth: 700,
    overflowY: "auto",
    padding: "0 10px",
  },
  card: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 12,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    boxShadow: "0 4px 10px rgba(0,0,0,0.1)",
    position: "relative",
  },
  infoContainer: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  nome: { fontWeight: 700, fontSize: 18, color: "#000" },
  endereco: { fontSize: 15, color: "#555" },
  deleteButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    position: "absolute",
    top: 10,
    right: 10,
  },

  // 🔹 Responsividade (Mobile)
  "@media (min-width: 600px)": {
    wrapper: { flexDirection: "row" },
    container: { paddingLeft: "100px" },
    card: { flexDirection: "row", alignItems: "center", gap: 40 },
  },
};
